# Generated by Django 3.0.8 on 2020-07-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='watching',
        ),
        migrations.AddField(
            model_name='user',
            name='watching',
            field=models.ManyToManyField(blank=True, related_name='watching', to='auctions.Auction'),
        ),
    ]
